#!/usr/bin/env python3
"""Deterministic operator-escalation gate (OPREQ ledger) — 2026-07-27.

Built after the operator found that `docs/ceo/cycle209-208a-operator-authorization-brief.md`
and `docs/ceo/cycle214-208a-amended-feasibility-result.md` contained a precise, real ask
("buy the complete Konak 2026/0003 tender packet") that was never actually surfaced to the
operator — it sat three files deep with no push notification and no durable, queryable
record of "this is still open."

This script is the ONLY thing that may:
  - decide whether an operator-request is genuinely new/changed and therefore worth a
    Telegram ping (dedup on a content fingerprint, not on presence alone);
  - mark a Telegram send as delivered (only after the Telegram API itself confirms
    `ok: true` — a non-erroring curl/urlopen call is not proof of delivery);
  - flip a request from OPEN to RESOLVED (requires a human-directive.md reference AND a
    type-specific DETERMINISTIC verification — a checksum-matched file on disk, a
    non-secret verification-log artifact, or a structured decision/authorization the
    OPERATOR wrote into human-directive.md — never a free-text claim the model wrote
    about itself; see verify_resolution() below);
  - regenerate the `## Awaiting Operator` section of consensus.md (a rendered projection,
    never a source of truth).

Source of truth for request content: memories/operator-requests.md (models append new
OPEN blocks here; this script never invents a request). Source of truth for
notification/dedup state: memories/.operator-requests-state.json — this file is written
ONLY by this script. Nothing in PROMPT.md ever instructs an agent to edit it directly;
agents that do so are violating policy, not exercising a legitimate write path.

Escalation-worthy types (the ONLY types that ever produce a Telegram notification or a
consensus.md projection entry) are documents, credentials, legal/financial decisions,
spend approval, external action beyond current authority, or a pending external
adjudication ruling — never a plain HOLD, UNKNOWN, research result, or informational
note. See ALLOWED_TYPES below.

Exit code is always 0 (never breaks the calling loop). All decisions are logged to
memories/operator-requests-audit.log.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

APP = Path(__file__).resolve().parents[2]

ALLOWED_TYPES = {
    "document-procurement",
    "credential",
    "legal-decision",
    "financial-decision",
    "expenditure-approval",
    "external-action-authorization",
    "adjudication-pending",
}

REQUIRED_FIELDS = [
    "Status",
    "Type",
    "Blocked scope",
    "Required input",
    "Acceptable response format",
    "Source brief",
    "Created",
]

TEMPLATE_HEADER = """# Operator Requests

<!-- Ledger of outstanding/resolved requests for operator-only input: documents,
     credentials, legal/financial decisions, spend approval, or external action beyond
     current authority. Agents APPEND a new '## OPREQ-<id>' block here when the company
     genuinely cannot proceed without such input -- never for ordinary HOLD, UNKNOWN,
     research-result, or informational output. See PROMPT.md "OPERATOR ESCALATION" for
     the exact field list and the resolution protocol.

     Notification/dedup state lives SEPARATELY in the code-owned file
     memories/.operator-requests-state.json, written only by
     scripts/core/operator_request_notify.py. Do not hand-edit that file, the
     '## Awaiting Operator' section of consensus.md (also code-generated), or the
     'Content fingerprint' field below (this script computes and rewrites it). -->
"""

BLOCK_RE = re.compile(r"^## (OPREQ-[A-Za-z0-9_-]+)\s*$", re.MULTILINE)
FIELD_RE = re.compile(r"^- ([A-Za-z][A-Za-z /]*):\s?(.*)$")
DIRECTIVE_STATUS_DONE_RE = re.compile(r"^## Status\s*\nDONE\b", re.MULTILINE)
RESOLVES_RE = re.compile(r"Resolves:\s*(OPREQ-[A-Za-z0-9_-]+)")
# Bare request id, for reading a target off a REFUSE line.
RESOLVES_RE_ID = re.compile(r"OPREQ-[A-Za-z0-9_-]+")

MAX_ATTEMPTS = 3
BACKOFF_SECONDS = [2, 4]

SECRET_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9]{10,}"),
    re.compile(r"Bearer\s+[A-Za-z0-9._-]{10,}", re.IGNORECASE),
    re.compile(r"\b[A-Za-z0-9_-]{32,}\b"),
]

PROJECTION_START = "\n\n## Awaiting Operator\n"
PROJECTION_NEXT_HEADING = "\n\n## "
PROJECTION_MARK = (
    "<!-- AUTO-GENERATED by scripts/core/operator_request_notify.py -- do not "
    "hand-edit; edit memories/operator-requests.md instead. -->"
)
PROJECTION_ANCHOR_AFTER = "\n\n## Active Projects\n"


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def norm_field(value: str) -> str:
    return re.sub(r"\s+", " ", value.strip())


def material_hash(fields: dict) -> str:
    parts = [
        norm_field(fields.get("Type", "")),
        norm_field(fields.get("Blocked scope", "")),
        norm_field(fields.get("Required input", "")),
        norm_field(fields.get("Acceptable response format", "")),
        norm_field(fields.get("Source brief", "")),
    ]
    material = "|".join(parts)
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def parse_fields(body: str) -> dict:
    fields: dict = {}
    cur_key = None
    for line in body.splitlines():
        m = FIELD_RE.match(line)
        if m:
            cur_key = m.group(1).strip()
            fields[cur_key] = m.group(2).strip()
        elif cur_key and line.strip() and not line.strip().startswith("<!--"):
            fields[cur_key] = (fields[cur_key] + " " + line.strip()).strip()
        elif not line.strip():
            cur_key = None
    return fields


def parse_blocks(text: str) -> dict:
    """Returns {req_id: (fields, (span_start, span_end))} — span covers the block's
    body (from just after the '## OPREQ-id' heading line to just before the next
    heading or EOF), used for precise in-place rewrites."""
    matches = list(BLOCK_RE.finditer(text))
    blocks = {}
    for i, m in enumerate(matches):
        req_id = m.group(1)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end]
        blocks[req_id] = (parse_fields(body), (start, end))
    return blocks


def validate_required(fields: dict) -> tuple[bool, list[str]]:
    missing = [f for f in REQUIRED_FIELDS if not fields.get(f, "").strip()]
    return (len(missing) == 0, missing)


def set_field_in_block_body(body: str, field_name: str, new_value: str) -> str:
    pattern = re.compile(
        rf"^- {re.escape(field_name)}:.*$(\n(?![-#\s]|$).+)*", re.MULTILINE
    )
    replacement = f"- {field_name}: {new_value}"
    if pattern.search(body):
        return pattern.sub(replacement, body, count=1)
    trimmed = body.rstrip("\n")
    sep = "\n" if trimmed else ""
    return trimmed + sep + f"\n- {field_name}: {new_value}\n"


def set_field_in_text(text: str, req_id: str, field_name: str, new_value: str) -> str:
    blocks = parse_blocks(text)
    if req_id not in blocks:
        return text
    _fields, (start, end) = blocks[req_id]
    body = text[start:end]
    new_body = set_field_in_block_body(body, field_name, new_value)
    return text[:start] + new_body + text[end:]


def scrub_secrets(text: str) -> str:
    out = text
    for pat in SECRET_PATTERNS:
        out = pat.sub("[REDACTED]", out)
    return out


def compose_message(req_id: str, fields: dict) -> str:
    lines = [
        f"\U0001f9d1‍\U0001f4bc OPERATOR INPUT NEEDED — {req_id}",
        f"Type: {fields.get('Type', '?')} | Blocks: {fields.get('Blocked scope', '?')}",
        "",
        f"Required: {fields.get('Required input', '')}",
        "",
        f"Reply via: {fields.get('Acceptable response format', '')}",
        f"Source: {fields.get('Source brief', '')}",
    ]
    msg = "\n".join(lines)
    return scrub_secrets(msg)[:3900]


def send_telegram(token: str, chat_id: str, text: str) -> tuple[bool, str | None]:
    data = urllib.parse.urlencode(
        {
            "chat_id": chat_id,
            "text": text,
            "disable_web_page_preview": "true",
        }
    ).encode()
    req = urllib.request.Request(
        f"https://api.telegram.org/bot{token}/sendMessage", data=data, method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.URLError as exc:
        return False, f"{type(exc).__name__}: {exc}"
    except Exception as exc:  # noqa: BLE001 - fail closed, never raise out of send
        return False, f"{type(exc).__name__}: {exc}"
    if body.get("ok") is True:
        return True, None
    return False, f"telegram api ok=false: {body.get('description', 'unknown')}"


def attempt_notify(token, chat_id, text, send_fn, sleep_fn):
    last_err = None
    for i in range(MAX_ATTEMPTS):
        ok, err = send_fn(token, chat_id, text)
        if ok:
            return True, None, i + 1
        last_err = err
        if i < MAX_ATTEMPTS - 1:
            sleep_fn(BACKOFF_SECONDS[i])
    return False, last_err, MAX_ATTEMPTS


def load_state(state_path: Path, audit_path: Path) -> dict:
    if not state_path.is_file():
        return {}
    try:
        return json.loads(state_path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001
        corrupt_backup = state_path.with_suffix(
            f".corrupt-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
        )
        try:
            corrupt_backup.write_bytes(state_path.read_bytes())
        except Exception:  # noqa: BLE001
            pass
        audit(
            audit_path,
            f"STATE-CORRUPT: {exc} — backed up to {corrupt_backup.name}, "
            "starting from empty dedup state (may re-notify once)",
        )
        return {}


def write_state(state_path: Path, state: dict) -> None:
    tmp = state_path.with_suffix(state_path.suffix + ".tmp")
    payload = json.dumps(state, indent=2, sort_keys=True) + "\n"
    tmp.write_text(payload, encoding="utf-8")
    tmp.replace(state_path)
    reloaded = state_path.read_text(encoding="utf-8")
    if reloaded != payload:
        raise RuntimeError("operator-requests state read-back mismatch")


def write_text_verified(path: Path, text: str) -> bool:
    path.write_text(text, encoding="utf-8")
    return path.read_text(encoding="utf-8") == text


def audit(audit_path: Path, msg: str) -> None:
    stamp = now_iso()
    with audit_path.open("a", encoding="utf-8") as f:
        f.write(f"[{stamp}] {msg}\n")


def render_projection_body(open_items: list[tuple[str, dict]]) -> str:
    if not open_items:
        return f"{PROJECTION_MARK}\n\nNone currently.\n"
    lines = [PROJECTION_MARK, ""]
    for req_id, fields in open_items:
        req_type = fields.get("Type", "?")
        scope = fields.get("Blocked scope", "?")
        required = fields.get("Required input", "")[:180]
        fmt = fields.get("Acceptable response format", "")[:160]
        source = fields.get("Source brief", "")
        lines.append(
            f"- **{req_id}** ({req_type}, blocks `{scope}`): {required}\n"
            f"  Reply: {fmt}\n"
            f"  Source: {source}"
        )
    return "\n".join(lines) + "\n"


def splice_projection(consensus_text: str, body: str) -> str:
    if PROJECTION_START in consensus_text:
        start = consensus_text.index(PROJECTION_START) + len(PROJECTION_START)
        rest = consensus_text[start:]
        nxt = rest.find(PROJECTION_NEXT_HEADING)
        end = start + nxt if nxt != -1 else len(consensus_text)
        return consensus_text[:start] + body.rstrip("\n") + "\n" + consensus_text[end:]
    if PROJECTION_ANCHOR_AFTER in consensus_text:
        # PROJECTION_ANCHOR_AFTER already ends in one "\n" (end of the "## Active
        # Projects" heading line) — add exactly one more so the inserted text starts
        # with the same "\n\n## Awaiting Operator\n" that PROJECTION_START looks for
        # on the next run. Getting this wrong (e.g. stripping to a single "\n") makes
        # the detector miss its own prior insertion and stack duplicate sections.
        idx = consensus_text.index(PROJECTION_ANCHOR_AFTER) + len(
            PROJECTION_ANCHOR_AFTER
        )
        return (
            consensus_text[:idx]
            + "\n## Awaiting Operator\n"
            + body.rstrip("\n")
            + "\n"
            + consensus_text[idx:]
        )
    return (
        consensus_text.rstrip("\n")
        + PROJECTION_START
        + body.rstrip("\n")
        + "\n"
    )


def process_notifications(text, state, audit_path, send_fn, sleep_fn):
    """Returns (possibly-updated text, possibly-updated state, changed: bool)."""
    changed = False
    blocks = parse_blocks(text)
    for req_id in sorted(blocks):
        fields, _span = blocks[req_id]
        status = fields.get("Status", "").strip().upper()
        if status != "OPEN":
            continue

        ok_fields, missing = validate_required(fields)
        if not ok_fields:
            audit(audit_path, f"MALFORMED {req_id}: missing fields {missing} — skipped")
            continue

        h = material_hash(fields)
        recorded_fp = fields.get("Content fingerprint", "")
        want_fp = f"sha256:{h}"
        if recorded_fp != want_fp:
            text = set_field_in_text(text, req_id, "Content fingerprint", want_fp)
            changed = True
            blocks = parse_blocks(text)
            fields, _span = blocks[req_id]

        req_type = fields.get("Type", "").strip().lower()
        if req_type not in ALLOWED_TYPES:
            audit(
                audit_path,
                f"IGNORED {req_id}: type={req_type!r} is not escalation-worthy — "
                "no notification, no projection entry",
            )
            continue

        st = state.get(req_id, {})
        already_notified = st.get("notified") is True and st.get(
            "material_content_hash"
        ) == h
        if already_notified:
            continue

        token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
        chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
        if not token or not chat_id:
            state[req_id] = {
                "material_content_hash": h,
                "notified": False,
                "notified_at": st.get("notified_at"),
                "retry_count": st.get("retry_count", 0),
                "last_error": "TELEGRAM_BOT_TOKEN/TELEGRAM_CHAT_ID unset",
                "last_attempt_at": now_iso(),
            }
            audit(audit_path, f"NOTIFY-SKIPPED {req_id}: Telegram not configured")
            continue

        msg = compose_message(req_id, fields)
        ok, err, attempts = attempt_notify(token, chat_id, msg, send_fn, sleep_fn)
        if ok:
            state[req_id] = {
                "material_content_hash": h,
                "notified": True,
                "notified_at": now_iso(),
                "retry_count": 0,
                "last_error": None,
                "last_attempt_at": now_iso(),
            }
            audit(audit_path, f"NOTIFIED {req_id} hash={h[:12]} attempts={attempts}")
        else:
            state[req_id] = {
                "material_content_hash": h,
                "notified": False,
                "notified_at": st.get("notified_at"),
                "retry_count": st.get("retry_count", 0) + attempts,
                "last_error": err,
                "last_attempt_at": now_iso(),
            }
            audit(
                audit_path,
                f"NOTIFY-FAILED {req_id} hash={h[:12]} attempts={attempts} error={err}",
            )

    return text, state, changed


EVIDENCE_DIR_NAME = "operator-evidence"

EVIDENCE_ENTRY_RE = re.compile(r"^(.+?)\s+sha256:([0-9a-fA-F]{64})$")
EXPECTED_COUNT_RE = re.compile(r"(\d+)\s*(?:file|dosya)", re.IGNORECASE)


def _resolve_evidence_path(app: Path, rel_path: str) -> Path | None:
    """Resolves rel_path against the app dir and confirms it stays inside
    memories/operator-evidence/ — refuses path traversal (../, absolute paths
    outside the sandbox) rather than silently reading whatever it lands on."""
    evidence_dir = (app / "memories" / EVIDENCE_DIR_NAME).resolve()
    candidate = (app / rel_path).resolve()
    try:
        candidate.relative_to(evidence_dir)
    except ValueError:
        return None
    return candidate


def verify_document_procurement(fields: dict, app: Path) -> tuple[bool, str]:
    raw = fields.get("Evidence files", "").strip()
    if not raw:
        return False, "no 'Evidence files' field"
    entries = [e.strip() for e in raw.split(";") if e.strip()]
    if not entries:
        return False, "'Evidence files' is empty"

    min_count = 1
    m = EXPECTED_COUNT_RE.search(fields.get("Expected document class", ""))
    if m:
        min_count = int(m.group(1))
    if len(entries) < min_count:
        return (
            False,
            f"only {len(entries)} evidence file(s) listed, 'Expected document "
            f"class' requires at least {min_count}",
        )

    for entry in entries:
        m2 = EVIDENCE_ENTRY_RE.match(entry)
        if not m2:
            return (
                False,
                f"malformed evidence entry {entry!r} — expected "
                "'<path under memories/operator-evidence/> sha256:<hex>'",
            )
        rel_path, expected_hash = m2.group(1).strip(), m2.group(2).lower()
        candidate = _resolve_evidence_path(app, rel_path)
        if candidate is None:
            return (
                False,
                f"evidence path {rel_path!r} is outside memories/{EVIDENCE_DIR_NAME}/ "
                "— refusing",
            )
        if not candidate.is_file():
            return False, f"evidence file missing: {rel_path}"
        if candidate.stat().st_size == 0:
            return False, f"evidence file is empty: {rel_path}"
        actual_hash = hashlib.sha256(candidate.read_bytes()).hexdigest()
        if actual_hash != expected_hash:
            return (
                False,
                f"checksum mismatch for {rel_path}: recorded {expected_hash[:12]}, "
                f"actual on-disk {actual_hash[:12]}",
            )
    return (
        True,
        f"{len(entries)} evidence file(s) verified on disk (exist, non-empty, "
        "checksum matches recorded value)",
    )


def verify_credential(fields: dict, app: Path) -> tuple[bool, str]:
    method = fields.get("Verification method", "").strip()
    result = fields.get("Verification result", "").strip()
    ts = fields.get("Verification timestamp", "").strip()
    log_rel = fields.get("Verification log", "").strip()
    missing = [
        name
        for name, val in [
            ("Verification method", method),
            ("Verification result", result),
            ("Verification timestamp", ts),
            ("Verification log", log_rel),
        ]
        if not val
    ]
    if missing:
        return False, f"missing field(s): {', '.join(missing)}"
    if result != "PASS":
        return False, f"'Verification result' is {result!r}, not PASS"

    candidate = _resolve_evidence_path(app, log_rel)
    if candidate is None:
        return (
            False,
            f"'Verification log' path {log_rel!r} is outside "
            f"memories/{EVIDENCE_DIR_NAME}/ — refusing",
        )
    if not candidate.is_file() or candidate.stat().st_size == 0:
        return False, f"verification log missing or empty: {log_rel}"
    log_text = candidate.read_text(encoding="utf-8", errors="replace")
    for pat in SECRET_PATTERNS:
        if pat.search(log_text):
            return (
                False,
                f"verification log at {log_rel} appears to contain a secret-shaped "
                "token — refusing to resolve; scrub it and re-record",
            )
    return (
        True,
        f"non-mutating auth test verification log present at {log_rel} "
        f"(method={method!r}), result=PASS, no secret-shaped content detected",
    )


def _directive_window_after(directive_text: str, anchor_label: str, req_id: str):
    pat = re.compile(rf"{anchor_label} for {re.escape(req_id)}:")
    m = pat.search(directive_text)
    if not m:
        return None
    rest = directive_text[m.end() :]
    cutoff = rest.find("OPREQ-")
    window = rest[:cutoff] if cutoff != -1 else rest
    return window[:1000]


DECISION_RE = re.compile(r"\s*([A-Za-z][A-Za-z -]{2,30}?)\s*[—-]\s*(.{10,})")


def verify_legal_or_financial_decision(
    req_id: str, directive_text: str
) -> tuple[bool, str]:
    window = _directive_window_after(directive_text, "Decision", req_id)
    if window is None:
        return (
            False,
            f"human-directive.md has no 'Decision for {req_id}: <word> — "
            "<rationale>' line",
        )
    m = DECISION_RE.match(window)
    if not m:
        return (
            False,
            f"'Decision for {req_id}:' found but not followed by "
            "'<word> — <rationale (>=10 chars)>'",
        )
    decision_word, rationale = m.group(1).strip(), m.group(2).strip()
    return (
        True,
        f"decision recorded in human-directive.md: {decision_word} — "
        f"{rationale[:80]}",
    )


def verify_authorization(req_id: str, directive_text: str) -> tuple[bool, str]:
    window = _directive_window_after(directive_text, "Authorization", req_id)
    if window is None:
        return False, f"human-directive.md has no 'Authorization for {req_id}:' block"
    values = {}
    for label in ("System", "Action", "Target", "Limit"):
        # `[ \t]*` and `[^\n]+`, NOT `\s*(.+)`: `\s` matches a newline, so an EMPTY
        # field used to swallow the following line as its own value. A directive with
        # a bare `System:` silently passed by capturing the `Action:` line, and a bare
        # `Limit:` captured the next paragraph — closing the request with a value the
        # operator never wrote, which is worse than leaving it open. The ledger tells
        # the operator "any missing or empty line leaves this request OPEN"; this makes
        # that true.
        m = re.search(rf"{label}:[ \t]*([^\n]+)", window)
        if m and m.group(1).strip():
            values[label] = m.group(1).strip()
    missing = [l for l in ("System", "Action", "Target", "Limit") if l not in values]
    if missing:
        return (
            False,
            f"'Authorization for {req_id}:' block missing: {', '.join(missing)}",
        )
    return (
        True,
        "authorization recorded: system={System!r} action={Action!r} "
        "target={Target!r} limit={Limit!r}".format(**values),
    )


# A refusal is a DECISION, not an absent answer, and it is valid for every request
# type — the operator declining to authorize is as final as authorizing. Until
# 2026-07-28 the ledger promised this ("to refuse instead, ... and the word REFUSE")
# and no code implemented it: a refusal fell through to the type verifier, failed for
# want of an authorization block, and left the request OPEN with only a RESOLVE-BLOCKED
# line in an audit file nobody reads.
#
# Uppercase and line-anchored on purpose. Prose discussing what a refusal would mean
# must not close a request, and `REFUSE` at the start of its own line is not something
# a sentence produces by accident.
REFUSE_RE = re.compile(r"^[ \t]*REFUSE\b[ \t]*:?[ \t]*(.*)$", re.MULTILINE)


def refusal_for(req_id: str, directive_text: str, resolves_ids: set) -> tuple[bool, str]:
    """Is THIS request refused by the directive? Fail closed when ambiguous."""
    matches = REFUSE_RE.findall(directive_text)
    if not matches:
        return False, ""
    named = {i for tail in matches for i in RESOLVES_RE_ID.findall(tail)}
    if named:
        # An explicit target always wins, and refuses only what it names.
        if req_id in named:
            reason = next(
                (t.strip() for t in matches if req_id in t and t.strip()), ""
            )
            return True, reason or "refused by name"
        return False, ""
    # A bare REFUSE is only unambiguous when the directive settles ONE request.
    # Refusing several at once by implication is exactly the kind of over-reach
    # this ledger exists to prevent.
    if len(resolves_ids) != 1:
        return (
            False,
            f"bare REFUSE but the directive resolves {len(resolves_ids)} requests — "
            "name the request on the REFUSE line to disambiguate",
        )
    reason = next((t.strip() for t in matches if t.strip()), "")
    return True, reason or "refused"


def verify_resolution(req_id: str, fields: dict, directive_text: str, app: Path):
    """Type-specific deterministic resolution check. The model's own prose can
    never close its own escalation — each type requires an objectively checkable
    artifact (a file's actual checksum, a structured decision the OPERATOR wrote
    into human-directive.md) rather than trusting a free-text claim."""
    req_type = fields.get("Type", "").strip().lower()
    if req_type == "document-procurement":
        return verify_document_procurement(fields, app)
    if req_type == "credential":
        return verify_credential(fields, app)
    if req_type in ("legal-decision", "financial-decision", "adjudication-pending"):
        # adjudication-pending reuses this verifier deliberately: applying an
        # external adjudicator's ruling is structurally the same act as the
        # operator recording a legal/financial decision -- a human transcribes
        # a real decision made outside the model into human-directive.md. The
        # model still cannot resolve its own escalation by asserting the
        # ruling arrived; the structured line must exist in the operator's own
        # directive text.
        return verify_legal_or_financial_decision(req_id, directive_text)
    if req_type in ("expenditure-approval", "external-action-authorization"):
        return verify_authorization(req_id, directive_text)
    return False, f"unrecognized type {req_type!r} — no verifier, refusing to resolve"


def process_resolutions(text, directive_text, audit_path, app: Path):
    changed = False
    directive_done = bool(DIRECTIVE_STATUS_DONE_RE.search(directive_text))
    resolves_ids = set(RESOLVES_RE.findall(directive_text))

    blocks = parse_blocks(text)
    for req_id in sorted(blocks):
        fields, _span = blocks[req_id]
        status = fields.get("Status", "").strip().upper()
        if status != "OPEN":
            continue
        if req_id not in resolves_ids:
            continue
        if not directive_done:
            audit(
                audit_path,
                f"RESOLVE-PENDING {req_id}: human-directive.md references it but "
                "Status is not yet DONE",
            )
            continue

        # Checked BEFORE the type verifier: a refusal is a complete answer, and
        # demanding an authorization block from someone who is declining to
        # authorize is incoherent.
        refused, why = refusal_for(req_id, directive_text, resolves_ids)
        if refused:
            text = set_field_in_text(text, req_id, "Status", "REFUSED")
            text = set_field_in_text(
                text, req_id, "Refusal recorded", f"{why} (at {now_iso()})"
            )
            changed = True
            audit(audit_path, f"REFUSED {req_id} via human-directive.md — {why}")
            continue
        if why:
            # An ambiguous refusal must not quietly become a non-refusal.
            audit(audit_path, f"REFUSE-AMBIGUOUS {req_id}: {why} — leaving OPEN")
            continue

        ok, detail = verify_resolution(req_id, fields, directive_text, app)
        if not ok:
            audit(
                audit_path,
                f"RESOLVE-BLOCKED {req_id}: directive is DONE and references it, "
                f"but deterministic verification failed — {detail} — leaving OPEN",
            )
            continue

        text = set_field_in_text(text, req_id, "Status", "RESOLVED")
        text = set_field_in_text(text, req_id, "Resolution verified", f"{detail} (at {now_iso()})")
        changed = True
        audit(audit_path, f"RESOLVED {req_id} via human-directive.md — {detail}")
    return text, changed


def _main_impl(app: Path, send_fn, sleep_fn) -> int:
    memories = app / "memories"
    requests_path = memories / "operator-requests.md"
    state_path = memories / ".operator-requests-state.json"
    audit_path = memories / "operator-requests-audit.log"
    consensus_path = memories / "consensus.md"
    directive_path = memories / "human-directive.md"

    memories.mkdir(parents=True, exist_ok=True)
    if not audit_path.is_file():
        audit_path.write_text("", encoding="utf-8")

    if not requests_path.is_file():
        requests_path.write_text(TEMPLATE_HEADER, encoding="utf-8")
        audit(audit_path, "INIT: created empty operator-requests.md")
        return 0

    text = requests_path.read_text(encoding="utf-8")
    state = load_state(state_path, audit_path)

    text, state, notif_changed = process_notifications(
        text, state, audit_path, send_fn, sleep_fn
    )

    # Persist notification/dedup state FIRST and independently of everything below.
    # A Telegram send is an irreversible side effect the moment the API returns
    # ok:true — if persisting the resulting `notified` flag were coupled to (and
    # could be lost by) a later, unrelated write failure, the next run would see no
    # record of the send and re-notify for the same content. This was caught live
    # on 2026-07-27: an operator-requests.md file left root-owned by an out-of-band
    # `docker exec` (not the app user the loop runs as) made the requests.md
    # rewrite below raise PermissionError, which — before this fix — propagated
    # uncaught and skipped the state write entirely, even though Telegram had
    # already been sent successfully.
    try:
        write_state(state_path, state)
    except Exception as exc:  # noqa: BLE001 - must never block on this
        audit(audit_path, f"STATE-WRITE-FAILED: {exc}")

    directive_text = (
        directive_path.read_text(encoding="utf-8") if directive_path.is_file() else ""
    )
    text, resolve_changed = process_resolutions(text, directive_text, audit_path, app)

    if notif_changed or resolve_changed:
        try:
            if not write_text_verified(requests_path, text):
                audit(
                    audit_path,
                    "WRITE-FAILED: operator-requests.md read-back mismatch — "
                    "fingerprint/resolution changes NOT persisted, will retry next run",
                )
        except Exception as exc:  # noqa: BLE001 - notification state is already safe
            audit(
                audit_path,
                f"WRITE-FAILED: operator-requests.md: {type(exc).__name__}: {exc} — "
                "fingerprint/resolution changes NOT persisted, will retry next run",
            )

    if consensus_path.is_file():
        try:
            final_blocks = parse_blocks(text)
            open_items = [
                (rid, fields)
                for rid, (fields, _span) in sorted(final_blocks.items())
                if fields.get("Status", "").strip().upper() == "OPEN"
                and fields.get("Type", "").strip().lower() in ALLOWED_TYPES
            ]
            consensus_text = consensus_path.read_text(encoding="utf-8")
            new_consensus = splice_projection(
                consensus_text, render_projection_body(open_items)
            )
            if new_consensus != consensus_text:
                if not write_text_verified(consensus_path, new_consensus):
                    audit(
                        audit_path,
                        "WRITE-FAILED: consensus.md read-back mismatch — projection "
                        "NOT updated, will retry next run",
                    )
        except Exception as exc:  # noqa: BLE001 - notification/resolution already safe
            audit(
                audit_path,
                f"WRITE-FAILED: consensus.md: {type(exc).__name__}: {exc} — "
                "projection NOT updated, will retry next run",
            )

    return 0


def main(app_dir: str | Path | None = None, send_fn=None, sleep_fn=None) -> int:
    app = Path(app_dir) if app_dir else APP
    send = send_fn or send_telegram
    sleep = sleep_fn or time.sleep
    try:
        return _main_impl(app, send, sleep)
    except Exception as exc:  # noqa: BLE001 - contract: never crash the calling loop
        try:
            audit_path = app / "memories" / "operator-requests-audit.log"
            audit(audit_path, f"UNCAUGHT-ERROR: {type(exc).__name__}: {exc}")
        except Exception:  # noqa: BLE001 - even the fallback log must not raise
            pass
        return 0


if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else None
    sys.exit(main(app_dir=arg))
